/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.cryptography;

import java.io.File;
import java.io.FileInputStream;
import java.io.FileOutputStream;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;

/**
 *
 * @author deand
 */
public class ImageEncrypterGUI extends javax.swing.JFrame {

    /**
     * Creates new form ImageEncrypterGUI
     */
    public ImageEncrypterGUI() {
        initComponents();
    }

    int Encryptionkey() {
        int key = Integer.parseInt(imageEncryptionTf.getText());
        return key;
    }

    void EncryptImage() {
        int key = Encryptionkey();
        JFileChooser obj = new JFileChooser();
        obj.showOpenDialog(null);
        File file = obj.getSelectedFile();

        try {
            FileInputStream obj1 = new FileInputStream(file);
            byte[] data = new byte[obj1.available()];
            obj1.read(data);
            int i = 0;
            for (byte b : data) {
                data[i] = (byte) (b ^ key);
                i++;
            }
            FileOutputStream obj2 = new FileOutputStream(file);
            obj2.write(data);
            obj2.close();
            obj1.close();
            JOptionPane.showMessageDialog(null, "Congratulations, The Image has been safely Encrypted");

        } catch (Exception e) {
            e.printStackTrace();

        }
    }

    int Decryptionkey() {
        int key = Integer.parseInt(imageDecryptionTf.getText());
        return key;
    }

    void DecryptImage() {
        int key = Decryptionkey();
        JFileChooser obj = new JFileChooser();
        obj.showOpenDialog(null);
        File file = obj.getSelectedFile();

        try {
            FileInputStream obj1 = new FileInputStream(file);
            byte[] data = new byte[obj1.available()];
            obj1.read(data);
            int i = 0;
            for (byte b : data) {
                data[i] = (byte) (b ^ key);
                i++;
            }
            FileOutputStream obj2 = new FileOutputStream(file);
            obj2.write(data);
            obj2.close();
            obj1.close();
            JOptionPane.showMessageDialog(null, "Congratulations, The Image has been safely Decrypted");

        } catch (Exception e) {
            e.printStackTrace();

        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        imageTitle = new javax.swing.JLabel();
        imageEncryptionTf = new javax.swing.JTextField();
        imageDecryptionTf = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        imageEncryptionBtn = new javax.swing.JButton();
        imageDecryptionBtn = new javax.swing.JToggleButton();
        imageEncryptKeyLbl = new javax.swing.JLabel();
        imageDecryptKeyLbl = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        imageTitle.setFont(new java.awt.Font("Algerian", 1, 24)); // NOI18N
        imageTitle.setText("Image Encrypter/Decrypter");

        jButton1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jButton1.setText("<- Back");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        imageEncryptionBtn.setBackground(new java.awt.Color(102, 153, 255));
        imageEncryptionBtn.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        imageEncryptionBtn.setText("Image Encryption");
        imageEncryptionBtn.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        imageEncryptionBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                imageEncryptionBtnActionPerformed(evt);
            }
        });

        imageDecryptionBtn.setBackground(new java.awt.Color(102, 153, 255));
        imageDecryptionBtn.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        imageDecryptionBtn.setText("Image Decryption");
        imageDecryptionBtn.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        imageDecryptionBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                imageDecryptionBtnActionPerformed(evt);
            }
        });

        imageEncryptKeyLbl.setText("Enter encryption key:");

        imageDecryptKeyLbl.setText("Enter decryption key:");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(imageDecryptionBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 248, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addContainerGap()
                                    .addComponent(jButton1))
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addGap(71, 71, 71)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                            .addComponent(imageEncryptionTf, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(imageDecryptionTf, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addComponent(imageEncryptionBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 248, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                        .addGap(0, 75, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(imageTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 383, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(51, 51, 51)
                .addComponent(imageEncryptKeyLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(imageDecryptKeyLbl)
                .addGap(61, 61, 61))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(imageTitle)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 44, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(imageDecryptKeyLbl)
                    .addComponent(imageEncryptKeyLbl))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(imageEncryptionTf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(imageDecryptionTf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(imageEncryptionBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(imageDecryptionBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButton1)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        setVisible(false);
        SoftwareAppsGUI obj = new SoftwareAppsGUI();
        obj.setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void imageEncryptionBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_imageEncryptionBtnActionPerformed
        if (imageEncryptionTf.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Ecryption key is needed.");
            return;
        } else {
            EncryptImage();
        }
    }//GEN-LAST:event_imageEncryptionBtnActionPerformed

    private void imageDecryptionBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_imageDecryptionBtnActionPerformed
        if (imageDecryptionTf.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Decryption key is needed.");
            return;
        } else {
            DecryptImage();
        }
    }//GEN-LAST:event_imageDecryptionBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ImageEncrypterGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ImageEncrypterGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ImageEncrypterGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ImageEncrypterGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ImageEncrypterGUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel imageDecryptKeyLbl;
    private javax.swing.JToggleButton imageDecryptionBtn;
    private javax.swing.JTextField imageDecryptionTf;
    private javax.swing.JLabel imageEncryptKeyLbl;
    private javax.swing.JButton imageEncryptionBtn;
    private javax.swing.JTextField imageEncryptionTf;
    private javax.swing.JLabel imageTitle;
    private javax.swing.JButton jButton1;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
